### ISSUE TITLE
NoSuchMethodError when trying to use KSPLogger

### ISSUE THREAD

**Issue by ansman** [google/ksp#103]
I'm trying to log messages using `KSPLogger.logging` but end up getting `NoSuchMethodError`: 
```
e: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.messages.MessageCollector$DefaultImpls.report$default(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity, java.lang.String, org.jetbrains.kotlin.cli.common.messages.CompilerMessageSourceLocation, int, java.lang.Object)'
	at com.google.devtools.ksp.processing.impl.MessageCollectorBasedKSPLogger.logging(MessageCollectorBasedKSPLogger.kt:43)
	at com.google.devtools.ksp.processing.KSPLogger$DefaultImpls.logging$default(KSPLogger.kt:25)
	at se.ansman.autoplugin.compiler.ksp.AutoPluginSymbolProcessor.log(AutoPluginSymbolProcessor.kt:115)

```

This is likely because KSP uses Kotlin 1.4 while Gradle 6.6.1 uses Kotlin 1.3.72. It would be nice if there was a workaround until Gradle 7 (which will use Kotlin 1.4).

Here is the project: https://github.com/ansman/auto-plugin/blob/4a35a4e90966e176fb9550cc9f68eab70781bbc1/compiler/src/main/kotlin/se/ansman/autoplugin/compiler/ksp/AutoPluginSymbolProcessor.kt#L115

To repro just check out the repo, uncomment [this line](https://github.com/ansman/auto-plugin/blob/4a35a4e90966e176fb9550cc9f68eab70781bbc1/gradle-plugin/src/funcTest/kotlin/se/ansman/autoplugin/gradle/AutoPluginGradlePluginKspTest.kt#L76) and run the test.

**Comment by ting-yuan** [comment]
I looked into auto-plugin a little bit and it looks like ksp's gradle plugin is applied by auto-plugin and somehow the compiler plugin is loaded by an older compiler (or at least with polluted classpath). Is that correct? Unfortunately, because there is no public / stable API from the compiler, KSP ties to specific compiler versions. In fact, one of KSP's design goal is to serve as a stable API layer of the compiler. So running KSP with older compiler isn't possible, at least for now.

**Comment by ting-yuan** [comment]
Note that KSP's API is backward compatible and so are processors. The only restriction is that processor users need to choose a matching version of KSP and compiler.
