### ISSUE TITLE
Is KSNode.validate() logical?

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1090]
As for an authritative function below
```
fun KSNode.validate(predicate: (KSNode?, KSNode) -> Boolean = { _, _ -> true }): Boolean {
    return this.accept(KSValidateVisitor(predicate), null)
}
```
and another part in KSValidateVisitor
```
  override fun visitDeclaration(declaration: KSDeclaration, data: KSNode?): Boolean {
      if (!predicate(data, declaration)) {
          return true
      }
      if (declaration.typeParameters.any { !it.accept(this, declaration) }) {
          return false
      }
      return this.visitAnnotated(declaration, data)
  }
```
I think 'predicate' should be for checking if an inner element is valid, so that any element violating 'predicate' makes the KSNode container invalid and return the result at once. Therefore,  the third line in the latter part should be 'return false'.

**Comment by neetopia** [comment]
this is not how `predicate` parameter works. 

The `predicate` parameter is there as a customizable input for processors to define which parts of the symbol they want to check, because different processors can have different requirements for the symbols' validity degree, for example, some processor may not care about the class body, only focuses on the constructor, and applying proper predicate allows them to ignore these useless information.
