### ISSUE TITLE
KSTypeParameter is a subclass of KSDeclaration, and owns inside typeParameters, isn't it improper?

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1092]

**Comment by neetopia** [comment]
In this case, the type parameter will simply be empty, a better abstraction might be abstracting out `KSTypeParameterListOwner` for this purpose, otherwise other APIs for KtDeclaration works well for `KSTypeParameter`, therefore the abstraction. Plus, this is also how compiler models type parameters.
