### ISSUE TITLE
Add KSTypeParameterContainer

### ISSUE THREAD

**Issue by IVIanuu** [google/ksp#115]
There's already `KSDeclarationContainer`, so I think it would be useful to add `KSTypeParameterContainer` as well.

**Comment by ting-yuan** [comment]
Type parameters can only appear in `KSDeclaration` according to [Kotlin grammar](https://kotlinlang.org/docs/reference/grammar.html):
```
typeParameters (used by typeAlias, classDeclaration, functionDeclaration, propertyDeclaration)
```

On the other hand, a `KSDeclarationContainer` can be a `KSFile`, `KSClassDeclaration` or `KSFunctionDeclaration`. Because they share nothing besides `KSAnnotated`, `KSDeclarationContainer` was introduced.

**Comment by IVIanuu** [comment]
Then maybe something like KsDeclarationWithTypeParameters or a extension?

It's quite inconvenient to do things like:

`val typeParams = when (declaration) {
    KSClassDeclaration -> ...
    KSFunctionDeclaration -> ...
    else -> error("Unexpected declaration")
}`

**Comment by bhargavms** [comment]
@IVIanuu I recommend using `.accept()` instead of writing when conditional loops.

**Comment by ting-yuan** [comment]
@IVIanuu When a `KSDeclaration` doesn't have type parameters, the `typeParameters` simply returns an empty list. The only one that always has a empty list is `KSTypeParameter`. I admit that the design less than perfect and people have to type check at runtime in order to distinguish this.On the other hand, can you give an example why the empty list is not enough and it must be known that it's because the underlying declaration is a `KSTypeParameter`?
