### ISSUE TITLE
Cache truly valid declarations

### ISSUE THREAD

**Issue by WilliamKwokX** [google/ksp#1240]
Declarations, from valid source code omitted by incremental mode or from libraries,  can be cached when users search them, which makes them quickly got and equal in different rounds.

**Comment by neetopia** [comment]
Valid declaration can still change its attributes with newly generated source, like new name shadowing affecting the resolve results for symbols, therefore it is not possible to cache symbols across rounds.

**Comment by neetopia** [comment]
KSP need to clear compiler environment for every round to ensure no legacy state is impacting new round of processing, generally speaking, declarations from libraries should be unchanged across rounds, but since compiler environment is changed, you still can't cache it, since you are unlikely to get same object again in new round.
