### ISSUE TITLE
Should `getClassDeclarationByName` mimic Kotlin Compiler?

### ISSUE THREAD

**Issue by yigit** [google/ksp#126]
Right now, if you request a java type explicitly from `getClassDeclarationByName`, it returns a KSType that specifically represnts the java type instead of its Kotlin counterpart.

e.g.
```
val kotlinType = resolver.getClassDeclarationByName("kotlin.String")
val javaType = resolver.getClassDeclarationByName("java.lang.String")
kotlinType == javaType // false
kotlinType.isAssignableFrom(javaType) // false
javaType.isAssingnableFrom(kotlinType) // false
```
On the other hand, if `java.lang.String` is every used in kotlin code or java code; it is always resolved to `kotlin.String`

e.g.

```
val x : String // type is kotlin.String!
val y : java.lang.String // type is kotlin.String!

// java
static String foo; // type is kotlin.String..kotlinString?
```

I'm wondering if it would be better (more consistent) if KSP behaved like the kotlin compiler where `getClassDeclarationByName` would return the kotlin type.
Otherwise, for an annotation processor that wants to support both java and kotlin, certain common functionalities becomes harder to write. e..g if it wants to check if a type is a `String`, it must check for `kotlin.String` AND `java.lang.String`. Even though, for individual cases, it seems feasible, it adds a burden on annotation processors to be aware of all types that have kotlin counterparts.

Here are some possible options:

a) Provide a mapper in resolver that receives the java name and returns the kotlin name (maybe even both ways). 
* this would be enough for room where we would always call it before getting the type to ensure Room is always in 1 realm (e.g. uses Kotlin types).

b) Change behavior of `getClassDeclarationByName` to always return the kotlin type, add another function to get java declaration.
* Even though this makes it more consistent with the kotlin compiler, it has the downside of the inconsistency where the qualified name of the returned class may not match the qualified name of the argument

c) Add an additional parameter to `getClassDeclarationByName` to specify the desired behavior.
* Makes the API more explicit but also more verbose.

d) Change all type methods to handle these cases. e.g. `isAssignableFrom` will return `true` for the case above (#125)
* I'm not actually sure if this is even feasible as it would also require equality to possibly return true or some other cases I cannot think of right now, hence could easily become inconsistent.

Creating this issue to discuss a path forward.

**Comment by ZacSweers** [comment]
I kind of like B, but an important distinction is to be able to determine which form the source element was. Particularly in Kotlin elements. I like D as well as a sort of orthogonal case, intrinsics should still be assignable

**Comment by ting-yuan** [comment]
d) has more overheads in current KSP and Kotlin compiler implementations. The mapping is done so that the type checker doesn't have to lookup in the table every time it performs type checking. Besides being requested explicitly (e.g., isAssignableFrom), type checking can also happens implicitly (e.g., overrides).

If users expect, for example, `kotlin.String` more often than `java.lang.String` from `getClassDeclarationByName("java.lang.String")` and don't feel it strange, it's straightforward to make it `getClassDeclarationByName(fqname: String, mapPlatformToKotlin: Boolean = true)` . This is somewhat a combination of b) and c). My only concern is whether it would be confusing to get `kotlin.String` by default while requesting `java.lang.String`.
