### ISSUE TITLE
Writing non-kotlin files outside of build directory using symbol processor

### ISSUE THREAD

**Issue by unredundant** [google/ksp#1340]
Hi! I'm chewing on an idea to use KSP to generate an [Atlas](https://atlasgo.io) schema from a set of annotated kotlin files.  However, two things are not obvious to me

1. Whether or not KSP processors can generate non-kotlin code (perhaps would require a custom implementation of the `CodeGenerator` interface?)
2. If there is a way to generate files outside of the `build` directory. In this case, would be preferable to have files generated inside of the `resources` folder, or perhaps even at the root of the module.

**Comment by neetopia** [comment]
1. KSP can generate any code, but code with extension names other than `.java` and `.kt` will be classified as resource files, it is user's responsibility to handle resource files separately. 
2. currently resource files are already generated into `build/<KSP generated folder>/resource` folder, is that what you are looking for? Speaking of generate files outside of `build` directory, you can try to specify `resourceOutputDir` option in KSP options when invoking KSP, it might not be configurable in Gradle extensions though, you can specify it in command line arguments.

**Comment by unredundant** [comment]
> it is user's responsibility to handle resource files separately

Could you expand on what this means? 

> currently resource files are already generated into build/<KSP generated folder>/resource

that's interesting and good to know, but no, what I want is to be able to generate files outside of the build folder, ideally to ultimately be checked into version control. Not a hard requirement, because in my workflow the atlas schema (HCL) is then compared to the schema on database, and ultimately converted into a flyway migration.  So it _can_ be stored in the build folder, but that would not be ideal.

**Comment by neetopia** [comment]
> Could you expand on what this means?
Basically resource files won't be packed into kotlin compilation therefore users should write their own logic to handle generated resource files, not a major blocker for you.

For your second request, you can achieve this in command line with relative path, but I won't expect running in command line works for most users, therefore an alternative in your case is to write a Gradle task to copy the content from generated folder to your VCS folder.

**Comment by unredundant** [comment]
Hmmm... that's sort of inconvenient :( 

What if I want to bundle this as a library that leverages KSP?  Then any users of the library would need to write a gradle task as well.

There's no way to tell the code writer to write to the module root instead of the build directory?

**Comment by neetopia** [comment]
writing to arbitrary folder can impose lots of unexpected results unknown to users which should not be encouraged. I actually don't see a strong reason to do so given that you can already add generated folder to your source set, is that due to the restrictions from the `Atlas` library you are trying to integrate into?

**Comment by unredundant** [comment]
The problem is that the atlas schema should be checked in to version control (unlike the generated source set).

**Comment by unredundant** [comment]
> writing to arbitrary folder can impose lots of unexpected results unknown to users which should not be encouraged

This seems like a wise general rule, but there are always exceptions to these sorts of things.

**Comment by neetopia** [comment]
It's too big risk to allow options interfering with Gradle's conventions, for your case probably it is better to write a copy task, it is inconvenient, but since this use case also seem to be limiting to Atlas, it should be a one off effort, I don't really expect checking in generated code is a common practice.

**Comment by unredundant** [comment]
Too big a risk to what exactly?  I don't follow your security argument here, there are plenty of gradle plugins that manipulate source code (ie formatters).

**Comment by neetopia** [comment]
formatter happens before compilation whereas KSP is part of the compilation pipeline, the use case isn't exactly same. The risk I can think of is more like interfering with the normal compilation pipeline since KSP is within this pipeline. Meanwhile, I don't really see annotation processor generated files getting checked into VCS very often, and writing a copy task in Gradle should serve your purpose if this is merely your use case.

**Comment by unredundant** [comment]
Not to argue semantics, but KSP must be before compilation as well? Otherwise how would the code actually compile?  Since in a users source code, they can reference the output generated by the KSP plugin. 

I'm no gradle expert, but I'm assuming that the KSP plugin attaches itself ahead of the actual compilation task in order for the appropriate source files to exist.

But that is all just me guessing.  

Personally, I don't agree w/ your argument but appreciate your input :) 

I will have to find a different solution, IMO it is not an acceptable solution for a library to simply expect every consumer to copy paste a gradle task into their source code in order to leverage the output.  

I'll leave it open to you / the other maintainers whether this ticket should remain open.

**Comment by neetopia** [comment]
KSP does run before compilation, KSP tasks can even be separately executed without compilation, but that's not the main point here. Being part of the compilation pipeline point comes from the fact that KSP Gradle plugin reads the Kotlin compile tasks in the project to construct/configure its tasks, therefore it is different from other tasks like formatter. 

For example, you can have multiple compile tasks sharing some source sets, if the code is generated into arbitrary directories, KSP tasks may end up overwriting each other's output, and the behavior is undefined, up to individual project's setup, whereas generating into build folder won't have this issue because build folder is not shared among different build targets.
