### ISSUE TITLE
Provide a way to access functions/methods/properties bodies (as a plain text)

### ISSUE THREAD

**Issue by bvitaliyg** [google/ksp#1349]
It's been stated that KSP doesn't aim to examine expression-level information of source code.

However, in some cases having access to raw code (e.g. in a format plain String) might be useful for some meta-programming tasks.

In my case, I need to gather some code samples, and copy its content into a markdown file, which is used later for the documentation samples on the website. Automating this will bring compilation checks to the sample code and simplify creating the documentation a lot.

No need to have access to any expression-level stuff – just the bodies as a plain string is more than enough.

In fact, `KSFunctionDeclarationImpl` already has access to `KSFunctionDeclarationImpl .ktFunction .text` and `KSFunctionDeclarationImpl .ktFunction.bodyBlockExpression`, so all that remaining is to provide a public access API for this property in something like `KSFunctionDeclaration.bodyText`. The same needs to be done for any body-containing entities.

I can make a PR if you're happy with the feature design and direction.

**Comment by neetopia** [comment]
The problem here is that this is subject to breaking changes from upstream compiler change, therefore potentially introducing maintenance overhead to us. 

Your approach should work independently without needing to add it to KSP's API, likely need to add a dependency to the KSP symbol implementations but it should work, and with that, you can actually just write your own library (and maybe you can also share libraries with other uses sharing same use case), but in general this should not be part of KSP's API.

One caveat is that this approach only works with current KSP implementation and will stop working when KSP supports new Kotlin compiler frontend....
