### ISSUE TITLE
@Target(AnnotationTarget.FIELD) no longer working

### ISSUE THREAD

**Issue by becky-sequence** [google/ksp#1409]
I'm trying to upgrade from gradle plugin version `1.8.0-1.0.8` to `1.8.20-1.0.11`. We have some field-level annotations that we use to drive processing. The annotations themselves are annotated with `@Target(AnnotationTarget.FIELD)`. I'm finding that with this version upgrade of the plugin these annotations are no longer available in the `annotations` sequence on `KSValueParameter`. I can't find any mention of this in the release notes - is this an intentional change? It feels like a bug to me. 

Removing the target type for our field-level annotations seems to cause other problems, so it would be good to resolve this.

**Comment by neetopia** [comment]
It is an intentional change to correct annotations to its places when specified by a use site target annotation. For you case, check to remove field target happens at [this line](https://github.com/google/ksp/blob/3c4c88abd24c99a7513a10b8f950b990947de3d1/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSValueParameterImpl.kt#L80). 

Reason for your case is that a field target means this annotation is meant for a backing field of a property which should not be available on a value parameter. Since you are applying target to be field, can I assume this value parameter is a value parameter in a primary constructor with a `val` or `var` keyword? If that's the case, you should be able to find your annotation in the corresponding `KSPropertyDeclaration`, if that is not the case, it seems to be a wrong usage of the annotation use site target to me.
