### ISSUE TITLE
KotlinCompilation.source has been deprecated in Kotlin 1.9.20-Beta

### ISSUE THREAD

**Issue by rickclephas** [google/ksp#1529]
See [KT-58234](https://youtrack.jetbrains.com/issue/KT-58234).
Projects using KSP 1.9.20-Beta-1.0.13 see the following warning during project sync:
```
w: `KotlinCompilation.source(KotlinSourceSet)` method is deprecated 
and will be removed in upcoming Kotlin releases.

See https://kotl.in/compilation-source-deprecation for details.
```

A quick search in the KSP sources resulted in the following usage of this API:
https://github.com/google/ksp/blob/d0b972dac7882b602a12ccc2689da7d4ede3eefa/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L558

**Comment by lwasyl** [comment]
I'll also link somewhat related issue: https://github.com/google/ksp/issues/1261 which actually seems pretty broken. For example `ktlint-gradle` plugin will grab all kotlin sourcesets: https://github.com/usefulness/ktlint-gradle-plugin/blob/db604241cf87ee59bbdcb9a3644fae16b7e46fac/ktlint-gradle-plugin/src/main/kotlin/io/github/usefulness/pluginapplier/KotlinSourceSetApplier.kt

When I log the source set name and it's `kotlin` `SourceDirectorySet`, I see the following:
![image](https://github.com/google/ksp/assets/3951580/e7ac7581-a265-4a98-a0f0-cc42c99057b0)

The problem is that `generatedByKsp*` source sets are compiled, when ktlint-gradle adds them to source inputs, my understanding is that Gradle will automatically wire up task dependencies. This makes `lintKotlin` task, which depends on `lintKotlinGeneratedByKsp*` task to _also_ depend on compilation tasks. 

This isn't the case with other plugins that generate files, which leads me to believe there is a more appropriate API that KSP could use

**Comment by SimonMarquis** [comment]
Yeah, this `generatedByKsp` also triggers errors within KMP with these kind of errors on expects/actuals:

```
Expected interface 'MyInterface' has no actual declaration in module my-module.generatedByKspKotlinJvm for JVM
```

**Comment by antohaby** [comment]
Hi! I'm Kotlin Gradle Plugin engineer at JetBrains. 

Yes, we are moving away from the possibility of including arbitrary KotlinSourceSet instances to compilation directly.
So Kotlin Compilation would have only a default source set which can have dependsOn relation to other source sets.

So in order to add sources to the compilation you can either:
1. Add dependsOn relation from default SourceSet of KotlinCompilation to freshly created Kotlin Source Set
2. Directly include sources to default  Source Set of KotlinCompilation like this:

```kotlin
compilation.defaultSourceSet.kotlin.srcDir("path/to/generated/code")
```

I would recommend going with option 2, because it is not necessary to spawn a new KotlinSourceSet instance that would have only one dependee.

Related information links:
* https://github.com/JetBrains/kotlin/blob/d4640cb57680e42fb34220811bb3bf545f0ffd44/libraries/tools/kotlin-gradle-plugin-api/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinCompilation.kt#L98
* https://kotl.in/compilation-source-deprecation

**Comment by lwasyl** [comment]
@antohaby Can you also share the recommended way to mark sources as generated (if it should be done by the plugin adding sources, like KSP), or have consuming Gradle plugins recognize and treat generated sources differently?
