### ISSUE TITLE
KSP2: default annotation arguments no longer work in 1.0.21

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1909]
Example using auto service

```java
public @interface AutoService {
  Class<?>[] value();
}
```

The below sample

```kotlin
@AutoService // <-- no args, so default [] is used
class CustomCallable : Callable<String> {
    override fun call(): String = "Hello world!"
}
```

Results in a `KSAnnotation` that reports that both `annotation.arguments` and `annotation.defaultArguments` are empty.

Repro is the failing test in https://github.com/ZacSweers/auto-service-ksp/pull/89

<img width="1470" alt="image" src="https://github.com/google/ksp/assets/1361086/b89ddbd3-4c2e-41db-b600-158430a4a0b9">

<img width="1464" alt="image" src="https://github.com/google/ksp/assets/1361086/c59b2011-ea34-4132-8cf1-ee06b177b372">

**Comment by ZacSweers** [comment]
This seems to be limited to `KClass` and annotation types. Primitives and enums appear to work

**Comment by neetopia** [comment]
To me it seems that this should never worked. The cause here is the default value is not explicitly declared in the source therefore it should get assigned automatically, KSP2 is parsing the binary class file to get the default value but the check failed to find a default value in the class file. Ideally we should assign a default value according to the type, which should be `[]` in your case. Let me try to find a way to assign default values in the event of implicit default values.

**Comment by neetopia** [comment]
It appears to have same issue in KSP1

**Comment by neetopia** [comment]
Hi @ZacSweers given this is also an issue in KSP1, do you know what's the last working version? I wonder if this is due to updates in the class file visitor versions if any.

At the same time, for this case in particular, I think I can try to manually assign default values based on the types of the annotation argument if that helps.

**Comment by ZacSweers** [comment]
This test passed on main, which is on `1.9.24-1.0.20`

**Comment by neetopia** [comment]
Per the language spec [JLS-9.6.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.2), annotations defined without a default value must have the corresponding value specified at use site, failed to do so should result in a compilation error. I feel this might be a mistake use case to apply a default value when there is no default value specified at declaration site.

With that being said, we still need to address the issue where we ignored the annotation values in case of a missing value use case. I will add a special default value for arrays but I will leave the rest of the default value types to return `null`, hope that will unblock you.
