### ISSUE TITLE
[KSP2] Class values in type annotations get resolved to error type

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1933]
This is similar to https://github.com/google/ksp/issues/1910. Class value is resolved to error type when the annotation is used on types and the origin is Java in KSP2, while it works in KSP1.

Repro: https://github.com/kuanyingchou/ksp/commit/55803265afaa46fd7a758de7a3d31b48958df033

**Comment by neetopia** [comment]
Issue is same as fix for this code: https://github.com/google/ksp/blob/00862a18967eed6832b28e081212e5f3250eb191/kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt#L486

This time however we can't fix it in KSP since it was resolved in AA already, we will need to fix the corresponding AA code for this https://github.com/JetBrains/kotlin/blob/71633b8e5ba49722170c9e06be87c058d11c985c/analysis/analysis-api-fir/src/org/jetbrains/kotlin/analysis/api/fir/evaluate/FirAnnotationValueConverter.kt#L192

**Comment by ting-yuan** [comment]
Fixed in AA as of build-2.1.0-dev-3498. https://github.com/JetBrains/kotlin/commit/afbb51129f9bbe126393823060699d9a97daed75
