### ISSUE TITLE
KSP memory leak in Android build

### ISSUE THREAD

**Issue by nico-gonzalez** [google/ksp#2073]
Hello! While investigating OOMs in our build we detected that heap space and metaspace is not being reclaimed after the build finishes, and mainly meta space keeps growing with each incremental build we run on both Gradle and Kotlin daemons.
It also seems that when ksp tasks run, the heap and meta space start to grow considerably

Is it possible that there is a memory leak somewhere in KSP?

Here's some info while running the heap dump through Eclipse MAT and Visual VM

<img width="1006" alt="Screenshot 2024-08-30 at 2 38 59 PM" src="https://github.com/user-attachments/assets/98123d80-3b9c-4829-8028-69f5d81a14b3">
<img width="1027" alt="Screenshot 2024-08-30 at 2 39 13 PM" src="https://github.com/user-attachments/assets/108b200d-6d3d-408e-a707-42f97a23ee2a">
<img width="1007" alt="Screenshot 2024-08-30 at 2 39 19 PM" src="https://github.com/user-attachments/assets/3a0f40eb-5919-42de-addb-d3292862c7fe">

<img width="1840" alt="Screenshot 2024-08-30 at 2 45 26 PM" src="https://github.com/user-attachments/assets/23e49182-28bd-4551-b895-7adb09b2867a">
<img width="1840" alt="Screenshot 2024-08-30 at 2 45 17 PM" src="https://github.com/user-attachments/assets/17206a84-d40d-4f57-8835-7c8d00300018">

I can share the heap dump if that's helpful. Let me know if you need anything else from my side to investigate this

**Comment by bnorm** [comment]
I may have found the root cause of this issue while investigating a reported memory leak in the Kotlin daemon: https://youtrack.jetbrains.com/issue/KT-72169.

I believe the custom implementation of ThreadLocal in [KSObjectCacheManager](https://github.com/google/ksp/blob/main/common-util/src/main/kotlin/com/google/devtools/ksp/common/KSObjectCacheManager.kt) is leaking the class loader due to never being removed from the thread. Adding `caches_prop.remove()` to the `clear()` function may be enough to fix this issue.

I also recommend that all other ThreadLocals used within KSP are removed during cleanup as well. I don't think they'll leak the class loader, but they will at least leak a class instance.

**Comment by kaeawc** [comment]
That looks like exactly what I was finding in my heap dumps investigating this issue. Thanks @bnorm !

**Comment by eygraber** [comment]
@ting-yuan I've been getting hit by this a lot. Any chance a fix can get into a coming release?
