### ISSUE TITLE
Cannot obtain docString of function inherited from parent class

### ISSUE THREAD

**Issue by ltttttttttttt** [google/ksp#2245]
Cannot obtain docString of function inherited from parent class

API: **KSFunctionDeclaration#docString**

**Handling Class A**

```kotlin
interface A : B {
    /**
     * doc
     */
    fun a()
}

interface B {
    /**
     * doc
     */
    fun b()
}
```

Function a can obtain doc
Function b can't obtain doc

**Comment by aochagavia** [comment]
Ran against this today. Is there any architectural limitation that prevents obtaining docStrings from items in other modules?

**Comment by jaschdoc** [comment]
Hi, could you provide a minimal example use of KSP and point out where you expect KSP returns the doc string for `B.b`? I believe I understand what the issue is, but I want to make sure we have a reference point for the issue.

**Comment by aochagavia** [comment]
Thanks for looking into this! I'm developing a library that can serve for showcasing the issue (it builds on top of KSP). While it's not a minimal reproducer, it might be useful regardless (let me know if it's too noisy, and I'll try to find the time to minimize it).

The relevant code is at the repository's [`tests-e2e` directory](https://github.com/aochagavia/krossover/tree/ccd26b3f0a1f5c34c7143ef9391b9ef2ce27ed94/tests-e2e), which has two Kotlin libraries:

- `core` (at `tests-e2e/core`): defines a `MyForeignClass` class with doc strings for both the class declaration and its one function.
- Root library (at `tests-e2e`): depends on `core` and references `MyForeignClass` in a public function's return type.

During the build, the root library collects metadata about the types in its public interface (using KSP) and generates a corresponding JSON file at `tests-e2e/build/generated/ksp/main/resources/krossover/api.json`. This file does contain an entry for `MyForeignClass`, but all doc strings are set to `null` (instead of to the actual doc strings). You can check the generated file yourself after running `./gradlew publishDev && ./gradlew -p tests-e2e jar` at the repository root.

**Comment by jaschdoc** [comment]
Thank you for the help. I can't promise when it will be fixed, but it's on the radar. To what degree do you depend on doc strings being available?

**Comment by aochagavia** [comment]
The tool I'm building is a bindings generator (it can generate e.g. a Python wrapper for your Kotlin library, with Python -> Kotlin calls going through the JNI). I think it's nice for users if the generated bindings are properly documented, hence the need for the doc strings. I can probably come up with a workaround on my side, but if the fix is not too complex on the KSP side (and there is enough reviewer bandwidth) I don't mind attempting a PR.

**Comment by jaschdoc** [comment]
I understand. There are other issues and features that have higher priority at the moment, but if you submit a PR I'd be happy to review it.

**Comment by aochagavia** [comment]
Thanks for the offer to review! I just spent some hours digging into this. I guess the root cause of the issue is obvious for existing contributors to KSP, but let me state it here to double-check I'm understanding things correctly and to inform anyone who is following along. As far as I can see, the problem is caused by two facts:

1. KSP obtains doc strings from the [Kotlin Analysis API](https://kotlin.github.io/analysis-api/index_md.html) (it wraps the `KaSymbol` type).
1. In the case of dependencies, KA seems to obtain that information from the compiled classes (which do not include doc comments).

In that light, it's entirely unsurprising that KSP lacks doc strings for dependencies. I don't know much about KA or KSP's internals, but this all sounds like a fix would require a non-trivial overhaul to the architecture, so it becomes possible to analyze the source code of dependencies instead of only their bytecode. Do you agree? If my description is accurate, it then looks like a proper solution would take more than some passer-by like me opening a PR. It involves too much design work and I'm afraid any efforts would quickly strand if the project's priorities are elsewhere. So... maybe the pragmatic option here is that people work around the doc string limitation.

**Comment by jaschdoc** [comment]
It's correct that if the doc comment is from a symbol in a compiled artifact, i.e., a jar or class file, then there's no clear way to obtain a doc string. Doing so would require maintaining a mapping from classes to sources and to also have the sources of the compiled artifact available. Does the problem persist if you have two sources files, each in different packages but in the same compilation unit? E.g.,
```kotlin
package com.example.pkg1

import com.example.pkg2.B

interface A : B
```
