### ISSUE TITLE
getSealedSubclasses() doesn't work with incremental processing in Kotlin-1.5

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#323]
Unfortunately the IC support in compiler is implemented explicitly rather than using lookup record, probably for better granularity.
https://github.com/JetBrains/kotlin/commit/36f99156fd140f1ef58c7763f88b5bca18926b15

Inserting mutual lookups ( super <-> sub classes ) should be able to fix it.

**Comment by ting-yuan** [comment]
> Inserting mutual lookups ( super <-> sub classes ) should be able to fix it.

Well, that is not enough. Any new file or change can affect the result of `getSealedSubclasses()`. What's needed is another form of dependency: All receivers of `getSealedSubclasses()` that were called need to be recorded. Then all changed class symbols need to be checked whether they extend those receivers.

**Comment by alexvanyo** [comment]
This might be an entirely separate issue, but I'm wondering how processors might interact if processors generate new sealed subclasses.

In particular, I'm thinking of the following case:

Processor A uses `getSealedSubclasses()` on round X, and Processor B generates a new sealed subclass for that class on round Y.

If X < Y, then I would expect that any outputs of Processor A might be invalid, since `getSealedSubclasses()` will have changed.

**Comment by ting-yuan** [comment]
Most symbol resolution results are also subject to this multiple round behavior. An obvious example is that processor A  waits for processor B to generate a definition that A has a reference to but could not resolve yet. A subtle case is that generated symbols can override the resolution results, causing that a reference is resolved to different definitions in different rounds of processing and in compiler.

Theoretically, KSP could reprocess files that have been invalidated due to newly generated symbols, but that would be very expensive and most of time unnecessary. Practically, it might be better to leave it to processors, as they have more context and can do it much more efficiently.
