### ISSUE TITLE
Feature request: Add `KSType.outerType` to access the outer class.

### ISSUE THREAD

**Issue by yamasa** [google/ksp#366]
## Feature request
- Add `outerType` property that returns the outer class if this `KSType` is an inner class.
  - If this type is not an inner class (e.g. top-level class, nested class, ...), `outerType` is null.
```kotlin
interface KSType {
    /** The outer type if this type is an inner class. */
    val outerType: KSType?
}
```

## Background
By https://github.com/google/ksp/issues/325, `KSType.arguments` returns *merged* type arguments if this type is an inner class.

```kotlin
class Outer<T> {
    inner class Inner<U>
}

val foo: Outer<String>.Inner<Int>
// fooPropertyDeclaration.type.resolve().arguments -> [Int, String]
```
However, even in the following cases, the values of `arguments` ​​are the same, so it is difficult to distinguish them.
```kotlin
class Outer {
    inner class Inner<T, U>
}

val foo: Outer.Inner<Int, String>
// fooPropertyDeclaration.type.resolve().arguments -> [Int, String]
```

```kotlin
class Outer<T, U> {
    inner class Inner
}

val foo: Outer<Int, String>.Inner
// fooPropertyDeclaration.type.resolve().arguments -> [Int, String]
```

I think this problem can be solved if `KSType` has an `outerType` property like kotlinx-metadata.
https://github.com/JetBrains/kotlin/blob/a5e445492fcd6cf3547bfef977ebd4dd489ee3ca/libraries/kotlinx-metadata/src/kotlinx/metadata/visitors.kt#L624-L637

```kotlin
class Outer<T> {
    inner class Inner<U>
}

val foo: Outer<String>.Inner<Int>
// fooPropertyDeclaration.type.resolve().arguments -> [Int]
// fooPropertyDeclaration.type.resolve().outerType?.arguments -> [String]
```

```kotlin
class Outer {
    inner class Inner<T, U>
}

val foo: Outer.Inner<Int, String>
// fooPropertyDeclaration.type.resolve().arguments -> [Int, String]
// fooPropertyDeclaration.type.resolve().outerType?.arguments -> []
```

```kotlin
class Outer<T, U> {
    inner class Inner
}

val foo: Outer<Int, String>.Inner
// fooPropertyDeclaration.type.resolve().arguments -> []
// fooPropertyDeclaration.type.resolve().outerType?.arguments -> [Int, String]
```

```kotlin
class Outer<T> {
    class Nested<U>
}

val foo: Outer.Nested<Int>
// fooPropertyDeclaration.type.resolve().arguments -> [Int]
// fooPropertyDeclaration.type.resolve().outerType -> null (`Nested` is not an inner class.)
```

**Comment by ting-yuan** [comment]
Hi @yamasa ,

Thanks for the proposal! It feels like to me that this is a choice between use cases:
1. Users care all type arguments more frequently.
2. Users care only type args of the inner type more frequently.

Both of the use cases can be satisfied with either current or the proposal. So it's probably a question of which one is more convenient.

From performance's point of view, the proposal has slightly more overhead because the outer type has to be created; Compiler doesn't keep the outer type in the inner type.

Therefore, I'm inclined to keep current API / behavior and, if that makes sense, provide the following extension properties: (names and details to be decided)
```
val KSType.outerType: KSType?
val KSType.innerArguments: List<KSTypeArgument>
```
What do you think?

btw, when applicable, it's more efficient to get the type arguments from the `KSTypeReference` which is resolved into the `KSType` in question.

**Comment by yamasa** [comment]
> 1. Users care all type arguments more frequently.
> 2. Users care only type args of the inner type more frequently.
>
> Both of the use cases can be satisfied with either current or the proposal. So it's probably a question of which one is more convenient.

I think a common use case in KSP is to get the type of a property in the source code and convert it to a `TypeName` of KotlinPoet to generate code.
In this case, it is more convenient to handle the OuterClass type and InnerClass type arguments separately.

In fact, the code I wrote does the conversion from `KSType` to `TypeName` in the following way.

https://github.com/line/lich/blob/0926990a851620fe9269e06aaaee2a3286b57158/savedstate-compiler/src/main/java/com/linecorp/lich/savedstate/compiler/KspViewModelArgsProcessor.kt#L171-L182

The current code does not correctly handle the case where the outer class has type arguments, but if my proposal is adopted, it will be able to handle it.

**Comment by ting-yuan** [comment]
I agree that sometimes it is more convenient to get only the declared type arguments, while sometimes it is the other way around. We still feel that it is better to stick with current behavior **in the core API** because trimming the information is always easier than reconstruction.

#408 Implements `outerType` as an extension property, as well as `innerArguments` to get type arguments that are declared directly by the current class.

For the purpose of computing `TypeName` in KotlinPoet, `arguments` can be replaced with `innerArguments`.

**Comment by ting-yuan** [comment]
#408 has landed. Please give it a try in next release and let us know what you think.

**Comment by yamasa** [comment]
@ting-yuan 
> #408 Implements `outerType` as an extension property, as well as `innerArguments` to get type arguments that are declared directly by the current class.

I think it is a good idea to implement them as extension properties.

> For the purpose of computing `TypeName` in KotlinPoet, `arguments` can be replaced with `innerArguments`.

Great! I've confirmed that it works as expected in my code.

Thanks!

**Comment by ting-yuan** [comment]
Glad to see that it works for you!
