### ISSUE TITLE
Consider exposing language version, api version, and jvm target as options

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#611]
This way processors can potentially tune their generated code as needed. This would be analogous to the declarations from the kotlin gradle plugin (`kotlinOptions.apiVersion`, `kotlinOptions.languageVersion`, `kotlinOptions.jvmTarget`)

**Comment by natario1** [comment]
It would be very useful to also have compilation information so that multiplatform processors know what platform is being compiled. Adding this here because it might make sense to address these things together, say with a sealed container - `jvmTarget` doesn't make sense for native, but something like `org.jetbrains.kotlin.konan.target.KonanTarget` would be very useful.

Use case: writing a processor for androidNative only, should throw if applied on other platforms. KonanTarget could be used for this.

**Comment by ting-yuan** [comment]
Language version is currently available via `SymbolProcessorEnvironment.kotlinVersion`, which is a [KotlinVersion](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-kotlin-version/). Others need to be added.

**Comment by ansman** [comment]
@ting-yuan It seems that `SymbolProcessorEnvironment.kotlinVersion` is not in fact the language version but rather the Kotlin version used. I'm using Kotlin 1.5.31 but have set the language version to 1.6 and `SymbolProcessorEnvironment.kotlinVersion` is still `1.5.31`.

**Comment by ting-yuan** [comment]
@ZacSweers @natario1 @ansman These properties are going to be introduced to `SymbolProcessorEnvironment`. Please let me know whether that makes sense.

```
class SymbolProcessorEnvironment(
    ...
    val apiVersion: KotlinVersion,
    val compilerVersion: KotlinVersion,
    val platforms: List<PlatformInfo>,
)
```
where
```
interface PlatformInfo {
    val platformName: String
}

interface JvmPlatformInfo : PlatformInfo {
    val jvmTarget: String
}

interface JsPlatformInfo : PlatformInfo

interface NativePlatformInfo : PlatformInfo {
    val targetName: String
}

interface UnknownPlatformInfo : PlatformInfo
```

Note that `platforms` is a list. This is because metadata compilation can have multiple underlying platforms.

Also, `SymbolProcessorEnvironment.kotlinVersion` will be fixed and return language version, as described in the API doc.
