### ISSUE TITLE
IllegalStateException: unhandled visibility: local

### ISSUE THREAD

**Issue by elihart** [google/ksp#613]
KSP is throwing an internal error within `fun MemberDescriptor.toKSModifiers` with the following stacktrace:
```
java.lang.IllegalStateException: unhandled visibility: local
        at com.google.devtools.ksp.symbol.impl.UtilsKt.toKSModifiers(utils.kt:178)
        at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl$modifiers$2.invoke(KSClassDeclarationDescriptorImpl.kt:123)
        at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl$modifiers$2.invoke(KSClassDeclarationDescriptorImpl.kt:121)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl.getModifiers(KSClassDeclarationDescriptorImpl.kt:121)
```

I haven't been able to track down the exact type causing the issue so I can't give a repro yet, but it seems like a straightforward case to add to the `when` statement.

The line numbers are out of date as we are using beta07 due to kotlin versioning restrictions, but I didn't see a fix in recent versions so it seems like it would still be an issue in the latest release.

**Comment by elihart** [comment]
I tracked down the specific offender. Our class has a property like this
```
    private var preDrawListener = object : ViewTreeObserver.OnPreDrawListener {
         ...
    }
```

So the property type is a local object instance, and looking up the modifiers on the type causes this crash.

A work around is to specify the type explicitly - `private var preDrawListener: ViewTreeObserver.OnPreDrawListener  = object : ViewTreeObserver.OnPreDrawListener `

**Comment by neetopia** [comment]
It appears to be a straightforward issue but actually I was having hard time reproduce it even with your reproduce code. Basically it looks that we are missing the handling for `local` descriptors for classes, but local should mean class declared in a function body, where descriptor impl means it is from library, but I am unable to reproduce a test case where I can reference a local class from a library, since they are most likely name mangled to avoid this to happen, like for 
```
class Foo {
    fun bar() {
        class Inner
    }
}
```
it will be `Foo$bar$Inner`, which does not seem to be the case in your code. Can you give me more details as to how to reproduce it? Like where is `ViewTreeObserver.OnPreDrawListener` declared, is it from library or source code, and if `private var preDrawListener` is from source or library?

**Comment by elihart** [comment]
Thanks for the update. I won't be able to try it for a while though as we first need to update our large project to kotlin 1.6.0, update Compose and other dependencies on the kotlin version, etc so it will be several weeks

**Comment by neetopia** [comment]
with #704 , it might be worth to consider a 1.5.31-1.0.1-RC . @ting-yuan thoughts?
