### ISSUE TITLE
Provide an API to read JvmDefaultMode

### ISSUE THREAD

**Issue by yigit** [google/ksp#627]
Room generates Java code that calls into Kotlin. For default methods, we need to know what JvmDefaultMode is passed in to generate the right code (to know whether kotlin compiler will generate DefaultImpls or use java's default methods in interfaces).

**Comment by danysantiago** [comment]
I was reminded on the need of this API recently due to a reported issue in Room: https://issuetracker.google.com/280831518.

Would be happy to contribute it with some direction on the API, not sure if a specific API for `-jvm-default` would be accepted or a more general one to expose kotlinc args used and then its up to processors to read the ones they are interested on.

**Comment by neetopia** [comment]
Speaking of the API itself, I think aggregating compiler args in an object makes more sense, and we can start with only exposing `jvm-default` flags in that object.
