### ISSUE TITLE
Incorrect nullability reported for type variables

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#82]
Given this snippet

```kotlin
@JsonClass(generateAdapter = true)
data class Example<T>(val nonNullT: T)
```

the `nonNullT` property reports its type as nullable (i.e. `property.type.resolve().nullability` is `NULLABLE`)

**Comment by yigit** [comment]
Actually, that example is not perfect because you can also have:

```
interface MyInterface<T>(val t:T)
class Instance : MyInterface<String?>
```
Now it should resolve to `nullable`. 

I was having a similar problem in Room where we have a custom `asMemberOf` implementation.
There, I found a workaround:
```
val explicitNullable = ksType.makeNullable() == this
```
This might help in your case too:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1441926/2/room/compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KSPropertyDeclarationExt.kt

**Comment by neetopia** [comment]
In compiler internal we have `KotlinType.isMarkedNullable` which can better serve this purpose. Yigit's workaround looks good but we are not sure if there can be any missing corner cases, and leveraging compiler API is more secure. 

In conclusion, an unbounded type parameter has an upper bound of `Any?` which should be considered as `nullable`, but we are going to expose `KotlinType.isMarkedNullable` for KSType, and then you can use that to check if a type parameter is explicitly marked as nullable with a question mark or not.

**Comment by ZacSweers** [comment]
Worked like a charm! Thanks for the tip @yigit, and looking forward to the public API fo this @neetopia 👍 

https://github.com/ZacSweers/MoshiX/pull/42
