### ISSUE TITLE
Compilation error is not thrown from KSPLogger logging error in `1.6.10-1.0.3`

### ISSUE THREAD

**Issue by seankim-android** [google/ksp#854]
I have a `SymbolProcessor` which was throwing a `KotlinCompilation.ExitCode.Compilation.ExitCode.COMPILATION_ERROR` from `environment.logger.error()` as expected in `1.0.2`. I have some unit tests to catch the error, which is now failing with `1.0.3` because it returns `KotlinCompilation.ExitCode.Compilation.ExitCode.OK`, and the `KSPLogger` API doesn't fail the compilation.

Is this intended? If so, is there a more preferred way to fail the compilation?

**Comment by ting-yuan** [comment]
Yes it is. It is changed from returning COMPILATION_ERROR to OK to workaround this issue:
https://youtrack.jetbrains.com/issue/KT-30172

All callers to the `AnalysisHandlerExtension` compiler plugin (KSP is one of them) in the compiler handle errors by checking error logs. Therefore in Gradle and command line users shouldn't notice the difference.

This reminds me that there can be issues when running from kotlin-compile-testing, for example 😢  May I know how you run KSP?

**Comment by ting-yuan** [comment]
btw, the upstream fix to KT-30172 is here: https://github.com/JetBrains/kotlin/pull/3950

We'll roll back to return COMPILATION_ERROR once it is merged.

**Comment by seankim-android** [comment]
Thanks @ting-yuan for your response! Is there a workaround for raising the `COMPILATION_ERROR` with ksp for the example test case provided in the post, or do we have wait for the upstream fix for this? I'm trying to see if there is another way to fail compilation without changing the unit test.

**Comment by ting-yuan** [comment]
Here is a [patch](https://github.com/tschuchortdev/kotlin-compile-testing/pull/244) to KCT to partially fix this problem: Unfortunately INTERNAL_ERROR is no longer possible; Any previous INTERNAL_ERROR in KSP becomes COMPILATION_ERROR until the fix lands in Kotlin compiler and KSP switches back.

I cannot think of any workaround in processors or outside of kotlin-compile-testing, because KSP always returns OK. It returns OK even when processor throws an exception.

**Comment by ting-yuan** [comment]
Fixed in another way in #865.
