### ISSUE TITLE
kapt and ksp are used together

### ISSUE THREAD

**Issue by Tobi1025** [google/ksp#895]
When my project use kapt and ksp together,i find that the compile time was getting longer than only use kapt.And the reason I use together with them is my library was used databinding，so i had to use "kotlin-kapt" plugin, but the router component was used ksp. So Could you tell me why the compile time  was getting longer when i used together, and how do databinding  support ksp？

**Comment by neetopia** [comment]
a major components in kapt task is stub generation, before actual java annotation processor processing can happen, and the benefit of adding ksp is to reduce the actual java ap time of a certain processor, but stub generation time is still there if kapt is still used, which is your case. 

Adding ksp should only add a minor time due to additional gradle task and compiler initialization, if this additional time is out-weighting the benefit of ksp, maybe you can try use the kapt version of the ksp processor.

**Comment by neetopia** [comment]
to answer your second question: currently databinding is not available on ksp.

**Comment by Tobi1025** [comment]
> 

ok,thanks for answer my question

**Comment by neetopia** [comment]
close as the question has been answered.
